resources:
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: emxartifactory 
      buildName: mvn_example_build
      buildNumber: 1
      
  - name: project_example
    type: GitRepo
    configuration:
      gitProvider:  github
      path: youngm/project-examples
 
pipelines:
  - name: mvn_example_build
    steps:
      - name: build_mvn
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: project_example
          integrations:
            - name: emxartifactory 
        execution:
          onStart:
            - _set_jdk openjdk8
            - javac -version
            - mvn --version
      - name: publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_mvn
          outputResources:
            - name: build_info
